services:
  mongo_user:
    image: mongo:6
    container_name: mongo_user
    ports:
      - "27018:27017"
    volumes:
      - mongo_user_data:/data/db

  mongo_todo:
    image: mongo:6
    container_name: mongo_todo
    ports:
      - "27019:27017"
    volumes:
      - mongo_todo_data:/data/db

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - "4001:4001"
    depends_on:
      - mongo_user
      - redis
    environment:
      - MONGO_URI=mongodb://mongo_user:27017/users
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=supersecretkey
    restart: unless-stopped

  todo-service:
    build: ./services/todo-service
    container_name: todo-service
    ports:
      - "4002:4002"
    depends_on:
      - mongo_todo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo_todo:27017/todos
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=supersecretkey
    restart: unless-stopped

  gateway:
    build: ./services/gateway
    container_name: gateway
    ports:
      - "4000:4000"
    depends_on:
      - user-service
      - todo-service
    environment:
      - USER_SERVICE_URL=http://user-service:4001/graphql
      - TODO_SERVICE_URL=http://todo-service:4002/graphql
    restart: unless-stopped
   

volumes:
  mongo_user_data:
  mongo_todo_data:


